#!/usr/bin/env python3
"""Regenerate plans/INDEX.md and validate the planning tournament's record.

The tournament keeps one plan file per planner per round, a score table with an evidence
line for every score, and one written justification per elimination. This script is the
authority on whether that record is internally consistent: the same frontmatter parser as
the roast log, the same discipline.

Usage:
    python scripts/plan_index.py            # rewrite INDEX.md from the round folders
    python scripts/plan_index.py --check    # exit 1 on drift or a broken trail

Exit codes:
    0  in sync (check) or written (default)
    1  drift, a broken trail, or inconsistent scores
    2  a malformed plan file
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

# Run as a script, sys.path[0] is this file's directory, so the shared frontmatter parser
# in scripts/ would not be importable without putting the repository root back on the path.
REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.roast_index import RoastLogError, parse_frontmatter  # noqa: E402

PLANS_DIR = REPO_ROOT / "plans"

INDEX_BEGIN = "<!-- plans:begin -->"
INDEX_END = "<!-- plans:end -->"
INDEX_HEADER = ("Round", "Planner", "Strategy family", "Thesis", "Status", "Weighted total", "Plan")
INDEX_PREAMBLE = """# Tournament Index

One row per plan per round, straight from the round folders. The table between the markers is
generated by `python scripts/plan_index.py` — edit the plans, not the table.

"""

ROUND_DIR_RE = re.compile(r"^r(?P<round>[1-9]\d*)$")
PLAN_FILENAME_RE = re.compile(r"^planner-(?P<letter>[a-d])\.md$")
FAMILY_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
URL_RE = re.compile(r"^https?://\S+$")

STATUSES = ("competing", "eliminated", "surviving")
DECISIONS = ("survives", "eliminated")
PLANNER_NAMES = tuple(f"planner-{letter}" for letter in "abcd")

REQUIRED_FIELDS = (
    "planner",
    "round",
    "strategy_family",
    "thesis",
    "date",
    "status",
    "sources_verified",
    "sources_unverified",
)
REQUIRED_SECTIONS = (
    "## Strategy",
    "## Architecture",
    "## Attribution",
    "## Interface",
    "## Schedule",
    "## Cost claims",
    "## Paper plan",
    "## Cut list",
    "## Sourcing ledger",
)
PLAN_MD_SECTIONS = REQUIRED_SECTIONS + ("## Rejected alternatives", "## Red team")

# (axis label used in SCORES.md, weight); weighted total is out of 42.
RUBRIC = (
    ("Feasibility", 3),
    ("Defensibility", 3),
    ("Sourcing", 2),
    ("Risk", 2),
    ("Interface", 2),
    ("Cost", 2),
)
MAX_TOTAL = sum(weight * 3 for _, weight in RUBRIC)

ROUND_HEADING_RE = re.compile(r"^## Round (?P<round>\d+)\s*$", re.MULTILINE)
SCORE_ROW_RE = re.compile(r"^\|\s*(?P<label>[A-Z])\s*\((?P<planner>planner-[a-d])\)\s*\|")
ELIMINATED_RE = re.compile(r"^\*\*Eliminated:\*\*\s*(?P<planner>planner-[a-d])\s*—(?P<reason>.+)$", re.MULTILINE)


class PlanLogError(Exception):
    """A plan file, a score table or the tournament trail is malformed."""


@dataclass(frozen=True)
class ScoreRow:
    label: str
    planner: str
    axes: tuple[int, ...]
    total: int
    decision: str

    def cells(self) -> list[str]:
        return [
            f"{self.label} ({self.planner})",
            *(str(value) for value in self.axes),
            str(self.total),
            self.decision,
        ]


@dataclass(frozen=True)
class Plan:
    planner: str
    round: int
    strategy_family: str
    thesis: str
    date: str
    status: str
    sources_verified: int
    sources_unverified: int
    path: Path

    @property
    def filename(self) -> str:
        return self.path.name

    @property
    def link(self) -> str:
        return f"r{self.round}/{self.filename}"

    def index_row(self, total: int | None) -> list[str]:
        return [
            str(self.round),
            self.planner,
            self.strategy_family,
            self.thesis,
            self.status,
            "—" if total is None else str(total),
            f"[{self.link}]({self.link})",
        ]


def _single_line(value: str, field: str, path: Path) -> str:
    if "|" in value:
        raise PlanLogError(f"{path}: frontmatter field {field!r} contains a '|', which breaks the index table")
    return value


def _int_field(fields: dict[str, str], key: str, path: Path) -> int:
    try:
        value = int(fields[key])
    except ValueError as error:
        raise PlanLogError(f"{path}: frontmatter field {key!r} must be an integer") from error
    if value < 0:
        raise PlanLogError(f"{path}: frontmatter field {key!r} must not be negative")
    return value


def parse_ledger(text: str, path: Path) -> tuple[int, int]:
    """Return (verified, unverified) counts from the sourcing ledger table."""
    start = text.find("## Sourcing ledger")
    if start == -1:
        raise PlanLogError(f"{path}: missing '## Sourcing ledger'")

    verified = 0
    unverified = 0
    for line in text[start:].splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [" ".join(cell.split()) for cell in line.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        claim, source, accessed = cells[0], cells[1], cells[2]
        if claim.lower() == "claim" or set(claim) <= {"-", ":", " "}:
            continue
        if source == "unverified":
            unverified += 1
            continue
        if not URL_RE.match(source):
            raise PlanLogError(
                f"{path}: sourcing ledger row {claim[:60]!r} has neither a URL nor the "
                "literal tag 'unverified'"
            )
        if not DATE_RE.match(accessed):
            raise PlanLogError(
                f"{path}: sourcing ledger row {claim[:60]!r} cites {source} without a "
                "YYYY-MM-DD access date"
            )
        verified += 1
    return verified, unverified


def load_plan(path: Path, round_number: int) -> Plan:
    """Parse and validate one plan file."""
    text = path.read_text(encoding="utf-8")

    name_match = PLAN_FILENAME_RE.match(path.name)
    if name_match is None:
        raise PlanLogError(f"{path}: plan filenames must look like 'planner-a.md'")

    try:
        fields = parse_frontmatter(text, path)
    except RoastLogError as error:
        raise PlanLogError(str(error)) from error
    for field in REQUIRED_FIELDS:
        if not fields.get(field):
            raise PlanLogError(f"{path}: frontmatter is missing a non-empty {field!r} field")

    planner = fields["planner"]
    if planner != f"planner-{name_match.group('letter')}":
        raise PlanLogError(f"{path}: frontmatter planner {planner!r} does not match the filename")
    if planner not in PLANNER_NAMES:
        raise PlanLogError(f"{path}: unknown planner {planner!r}")

    if fields["round"] != str(round_number):
        raise PlanLogError(
            f"{path}: frontmatter round {fields['round']!r} does not match its folder r{round_number}"
        )
    if not FAMILY_RE.match(fields["strategy_family"]):
        raise PlanLogError(f"{path}: strategy_family {fields['strategy_family']!r} must be kebab-case")
    if fields["status"] not in STATUSES:
        raise PlanLogError(
            f"{path}: status {fields['status']!r} is not one of {', '.join(STATUSES)}"
        )
    if not DATE_RE.match(fields["date"]):
        raise PlanLogError(f"{path}: date {fields['date']!r} must be YYYY-MM-DD")

    thesis = _single_line(fields["thesis"], "thesis", path)
    if not thesis.strip():
        raise PlanLogError(f"{path}: thesis must not be empty")

    positions = []
    for section in REQUIRED_SECTIONS:
        index = text.find(f"\n{section}")
        if index == -1:
            raise PlanLogError(f"{path}: missing required section {section!r}")
        positions.append(index)
    if positions != sorted(positions):
        raise PlanLogError(
            f"{path}: sections are out of order; expected {' '.join(REQUIRED_SECTIONS)}"
        )

    verified, unverified = parse_ledger(text, path)
    if verified != _int_field(fields, "sources_verified", path):
        raise PlanLogError(
            f"{path}: frontmatter says sources_verified: {fields['sources_verified']} but the "
            f"ledger lists {verified}"
        )
    if unverified != _int_field(fields, "sources_unverified", path):
        raise PlanLogError(
            f"{path}: frontmatter says sources_unverified: {fields['sources_unverified']} but the "
            f"ledger lists {unverified}"
        )

    return Plan(
        planner=planner,
        round=round_number,
        strategy_family=fields["strategy_family"],
        thesis=thesis,
        date=fields["date"],
        status=fields["status"],
        sources_verified=verified,
        sources_unverified=unverified,
        path=path,
    )


def discover_rounds(plans_dir: Path) -> dict[int, list[Plan]]:
    """Load every round folder, keyed by round number, sorted by planner."""
    rounds: dict[int, list[Plan]] = {}
    for directory in sorted(plans_dir.glob("r*")):
        if not directory.is_dir():
            continue
        match = ROUND_DIR_RE.match(directory.name)
        if match is None:
            continue
        number = int(match.group("round"))
        plans = [load_plan(path, number) for path in sorted(directory.glob("*.md"))]
        if plans:
            rounds[number] = plans
    return rounds


def _cell(line: str) -> list[str]:
    stripped = line.strip()
    if stripped.startswith("|"):
        stripped = stripped[1:]
    if stripped.endswith("|"):
        stripped = stripped[:-1]
    return [" ".join(part.split()) for part in stripped.split("|")]


def score_blocks(text: str) -> dict[int, str]:
    """Split SCORES.md into one text block per round heading."""
    blocks: dict[int, str] = {}
    matches = list(ROUND_HEADING_RE.finditer(text))
    for position, match in enumerate(matches):
        number = int(match.group("round"))
        end = matches[position + 1].start() if position + 1 < len(matches) else len(text)
        blocks[number] = text[match.end() : end]
    return blocks


def parse_scores(text: str, path: Path) -> dict[int, list[ScoreRow]]:
    """Parse SCORES.md into one row list per round."""
    sections: dict[int, list[ScoreRow]] = {}
    for number, block in score_blocks(text).items():
        rows: list[ScoreRow] = []
        for line in block.splitlines():
            row_match = SCORE_ROW_RE.match(line.strip())
            if row_match is None:
                continue
            cells = _cell(line)
            if len(cells) < len(RUBRIC) + 3:
                raise PlanLogError(f"{path}: round {number} score row has too few cells: {line.strip()!r}")
            try:
                axes = tuple(int(cells[index + 1]) for index in range(len(RUBRIC)))
                total = int(cells[len(RUBRIC) + 1])
            except ValueError as error:
                raise PlanLogError(
                    f"{path}: round {number} score row {row_match.group('label')} has a non-integer score"
                ) from error
            for value in axes:
                if not 0 <= value <= 3:
                    raise PlanLogError(
                        f"{path}: round {number} score row {row_match.group('label')} has axis "
                        f"score {value}; axes are 0-3"
                    )
            decision = cells[len(RUBRIC) + 2].lower()
            if decision not in DECISIONS:
                raise PlanLogError(
                    f"{path}: round {number} score row {row_match.group('label')} has decision "
                    f"{cells[len(RUBRIC) + 2]!r}, expected one of {', '.join(DECISIONS)}"
                )
            rows.append(
                ScoreRow(
                    label=row_match.group("label"),
                    planner=row_match.group("planner"),
                    axes=axes,
                    total=total,
                    decision=decision,
                )
            )
        if rows:
            sections[number] = rows
    return sections


def weighted_total(axes: tuple[int, ...]) -> int:
    return sum(value * weight for value, (_, weight) in zip(axes, RUBRIC))


def check_trail(rounds: dict[int, list[Plan]]) -> list[str]:
    """Validate round sizes, contiguity, strategy diversity and the elimination trail."""
    problems: list[str] = []
    if not rounds:
        return ["plans/: no rounds found; the tournament has not started"]

    numbers = sorted(rounds)
    if numbers != list(range(1, len(numbers) + 1)):
        problems.append(f"plans/: rounds are not contiguous from r1; found {numbers}")
        return problems

    if len(rounds[1]) != len(PLANNER_NAMES):
        problems.append(
            f"plans/r1/: round one must run all {len(PLANNER_NAMES)} planners, found {len(rounds[1])}"
        )

    for number in numbers:
        plans = rounds[number]
        families: dict[str, str] = {}
        for plan in plans:
            if plan.strategy_family in families:
                problems.append(
                    f"{plan.path}: strategy family {plan.strategy_family!r} is already claimed by "
                    f"{families[plan.strategy_family]}; the round is not diverse"
                )
            families[plan.strategy_family] = plan.planner

        eliminated = [plan for plan in plans if plan.status == "eliminated"]
        survivors = [plan for plan in plans if plan.status == "surviving"]
        is_last = number == numbers[-1]

        if len(eliminated) > 1:
            problems.append(f"plans/r{number}/: {len(eliminated)} plans marked eliminated, expected one")
        if survivors and not is_last:
            problems.append(f"plans/r{number}/: a plan is marked surviving but r{number} is not the last round")
        if len(survivors) > 1:
            problems.append(f"plans/r{number}/: {len(survivors)} plans marked surviving, expected one")

        if not is_last:
            if len(eliminated) != 1:
                problems.append(
                    f"plans/r{number}/: a completed round must eliminate exactly one plan, found {len(eliminated)}"
                )
            else:
                expected_next = {plan.planner for plan in plans} - {eliminated[0].planner}
                actual_next = {plan.planner for plan in rounds[number + 1]}
                if expected_next != actual_next:
                    missing = sorted(expected_next - actual_next)
                    extra = sorted(actual_next - expected_next)
                    problems.append(
                        f"plans/r{number + 1}/: competitors must be the survivors of r{number}; "
                        f"missing {missing}, unexpected {extra or ['none']}"
                    )
                if len(rounds[number + 1]) != len(plans) - 1:
                    problems.append(
                        f"plans/r{number + 1}/: {len(rounds[number + 1])} plans after a round of "
                        f"{len(plans)}; exactly one planner is eliminated per round"
                    )
        elif eliminated and not survivors:
            problems.append(
                f"plans/r{number}/: the last round eliminated a plan but nothing is marked surviving"
            )
    return problems


def check_scores(rounds: dict[int, list[Plan]], scores_text: str, scores_path: Path) -> list[str]:
    """Validate score arithmetic, decisions and their agreement with plan frontmatter."""
    problems: list[str] = []
    try:
        sections = parse_scores(scores_text, scores_path)
    except PlanLogError as error:
        return [str(error)]

    for number, plans in sorted(rounds.items()):
        eliminated = [plan for plan in plans if plan.status == "eliminated"]
        complete = number != max(rounds) or bool(eliminated)
        if not complete:
            continue
        if number not in sections:
            problems.append(f"{scores_path}: round {number} has no score table")
            continue

        rows = sections[number]
        by_planner = {row.planner: row for row in rows}
        for plan in plans:
            if plan.planner not in by_planner:
                problems.append(f"{scores_path}: round {number} never scored {plan.planner}")

        labels = [row.label for row in rows]
        if len(set(labels)) != len(labels):
            problems.append(f"{scores_path}: round {number} reuses an anonymized label")

        decision_rows = [row for row in rows if row.decision == "eliminated"]
        if len(decision_rows) != 1:
            problems.append(
                f"{scores_path}: round {number} marks {len(decision_rows)} rows eliminated, expected one"
            )
        for row in rows:
            expected_total = weighted_total(row.axes)
            if row.total != expected_total:
                problems.append(
                    f"{scores_path}: round {number} row {row.label} totals {row.total} but its axis "
                    f"scores weigh to {expected_total} of {MAX_TOTAL}"
                )

        block = score_blocks(scores_text).get(number, "")
        justification = ELIMINATED_RE.search(block)
        if justification is None:
            problems.append(
                f"{scores_path}: no '**Eliminated:** planner-x — reason' line; every elimination needs "
                "a written justification"
            )
        if eliminated:
            if decision_rows and decision_rows[0].planner != eliminated[0].planner:
                problems.append(
                    f"{scores_path}: round {number} eliminates {decision_rows[0].planner} but "
                    f"{eliminated[0].path} is marked eliminated"
                )
            if justification and justification.group("planner") != eliminated[0].planner:
                problems.append(
                    f"{scores_path}: the elimination justification names "
                    f"{justification.group('planner')} but {eliminated[0].planner} left the round"
                )
    return problems


def check_final_plan(rounds: dict[int, list[Plan]], plans_dir: Path) -> list[str]:
    """Require PLAN.md once a survivor exists, with the required sections."""
    survivors = [plan for plans in rounds.values() for plan in plans if plan.status == "surviving"]
    path = plans_dir / "PLAN.md"
    if not survivors:
        if path.exists():
            return [f"{path}: exists but no plan is marked surviving"]
        return []

    problems: list[str] = []
    if not path.exists():
        return [f"{path}: the tournament produced a survivor but PLAN.md does not exist"]

    text = path.read_text(encoding="utf-8")
    for section in PLAN_MD_SECTIONS:
        if f"\n{section}" not in text:
            problems.append(f"{path}: missing required section {section!r}")
    if survivors[0].strategy_family not in text:
        problems.append(
            f"{path}: does not name the surviving strategy family {survivors[0].strategy_family!r}"
        )
    if "## Red team" in text and len(text.split("## Red team", 1)[1].split()) < 20:
        problems.append(f"{path}: the red-team section is empty; the eliminated planners' critiques belong there")
    return problems


def index_rows(rounds: dict[int, list[Plan]], scores: dict[int, list[ScoreRow]]) -> list[list[str]]:
    rows: list[list[str]] = []
    for number in sorted(rounds):
        totals = {row.planner: row.total for row in scores.get(number, [])}
        for plan in rounds[number]:
            rows.append(plan.index_row(totals.get(plan.planner)))
    return rows


def render_table(rows: list[list[str]]) -> str:
    lines = [
        "| " + " | ".join(INDEX_HEADER) + " |",
        "| " + " | ".join(":---" for _ in INDEX_HEADER) + " |",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines)


def render_index(existing: str | None, rows: list[list[str]]) -> str:
    region = f"{INDEX_BEGIN}\n\n{render_table(rows)}\n\n{INDEX_END}"
    if existing:
        start = existing.find(INDEX_BEGIN)
        end = existing.find(INDEX_END)
        if start != -1 and end != -1 and end > start:
            return existing[:start] + region + existing[end + len(INDEX_END) :]
    return f"{INDEX_PREAMBLE}{region}\n"


def actual_rows(index_text: str, path: Path) -> list[list[str]]:
    start = index_text.find(INDEX_BEGIN)
    end = index_text.find(INDEX_END)
    if start == -1 or end == -1 or end < start:
        raise PlanLogError(
            f"{path}: missing the '{INDEX_BEGIN}' / '{INDEX_END}' markers that bracket the table"
        )
    rows: list[list[str]] = []
    for line in index_text[start + len(INDEX_BEGIN) : end].splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = _cell(line)
        if [cell.lower() for cell in cells] == [column.lower() for column in INDEX_HEADER]:
            continue
        if all(re.fullmatch(r":?-{2,}:?", cell) for cell in cells):
            continue
        rows.append(cells)
    return rows


def find_problems(plans_dir: Path) -> list[str]:
    """Validate the whole tournament record; empty means consistent."""
    rounds = discover_rounds(plans_dir)
    problems = check_trail(rounds)
    if problems:
        return problems

    scores_path = plans_dir / "SCORES.md"
    scores: dict[int, list[ScoreRow]] = {}
    if scores_path.exists():
        scores_text = scores_path.read_text(encoding="utf-8")
        problems.extend(check_scores(rounds, scores_text, scores_path))
        try:
            scores = parse_scores(scores_text, scores_path)
        except PlanLogError:
            scores = {}
    elif any(plan.status == "eliminated" for plans in rounds.values() for plan in plans):
        problems.append(f"{scores_path}: does not exist but the tournament has eliminated a plan")

    problems.extend(check_final_plan(rounds, plans_dir))

    index_path = plans_dir / "INDEX.md"
    expected = index_rows(rounds, scores)
    if not index_path.exists():
        problems.append(f"{index_path}: does not exist; run 'python scripts/plan_index.py' to generate it")
        return problems

    try:
        actual = actual_rows(index_path.read_text(encoding="utf-8"), index_path)
    except PlanLogError as error:
        return problems + [str(error)]

    if len(actual) != len(expected):
        problems.append(
            f"{index_path}: has {len(actual)} row(s) for {len(expected)} plan file(s); run "
            "'python scripts/plan_index.py' to regenerate the table"
        )
        return problems
    for expected_row, actual_row in zip(expected, actual):
        if expected_row == actual_row:
            continue
        for column, expected_cell, actual_cell in zip(INDEX_HEADER, expected_row, actual_row):
            if expected_cell != actual_cell:
                problems.append(
                    f"{index_path}: row {expected_row[0]}/{expected_row[1]} column {column!r} says "
                    f"{actual_cell!r} but the plan says {expected_cell!r}"
                )
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="verify the record instead of rewriting INDEX.md"
    )
    parser.add_argument(
        "--plans-dir",
        type=Path,
        default=PLANS_DIR,
        help="directory holding the tournament record (default: <repo>/plans)",
    )
    args = parser.parse_args(argv)
    plans_dir: Path = args.plans_dir
    index_path = plans_dir / "INDEX.md"

    try:
        rounds = discover_rounds(plans_dir)
    except (PlanLogError, RoastLogError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.check:
        try:
            problems = find_problems(plans_dir)
        except (PlanLogError, RoastLogError) as error:
            print(f"error: {error}", file=sys.stderr)
            return 2
        if problems:
            for problem in problems:
                print(f"error: {problem}", file=sys.stderr)
            return 1
        print(f"ok: {sum(len(plans) for plans in rounds.values())} plan(s) across {len(rounds)} round(s)")
        return 0

    scores: dict[int, list[ScoreRow]] = {}
    scores_path = plans_dir / "SCORES.md"
    if scores_path.exists():
        try:
            scores = parse_scores(scores_path.read_text(encoding="utf-8"), scores_path)
        except PlanLogError as error:
            print(f"error: {error}", file=sys.stderr)
            return 2
    existing = index_path.read_text(encoding="utf-8") if index_path.exists() else None
    index_path.write_text(render_index(existing, index_rows(rounds, scores)), encoding="utf-8")
    print(f"wrote {index_path} with {sum(len(plans) for plans in rounds.values())} plan(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
