#!/usr/bin/env python3
"""Regenerate roasts/INDEX.md from the ruling files, or verify that it is in sync.

The Idea Roast Council's Judge writes one ruling file per idea. This script is the
single source of truth for the index table that summarises them, so the table cannot
quietly drift away from the rulings it claims to describe.

Usage:
    python scripts/roast_index.py            # rewrite INDEX.md from the rulings
    python scripts/roast_index.py --check    # exit 1 if INDEX.md has drifted

Exit codes:
    0  in sync (check) or written (default)
    1  drift detected
    2  malformed ruling (missing or invalid frontmatter, bad filename, duplicates)
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

INDEX_BEGIN = "<!-- index:begin -->"
INDEX_END = "<!-- index:end -->"
INDEX_HEADER = ("#", "Idea", "Date", "Verdict", "Biggest risk", "Questions", "Ruling")
INDEX_PREAMBLE = """# Ruling Index

One row per ruling the council has handed down, newest rulings last. The table between the
markers below is generated by `python scripts/roast_index.py` — edit the rulings, not the table.

"""

RULING_FILENAME_RE = re.compile(r"^(?P<id>\d{3})-(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)\.md$")
FRONTMATTER_RE = re.compile(r"\A---[ \t]*\r?\n(?P<body>.*?)\r?\n---[ \t]*\r?\n", re.DOTALL)
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

VERDICTS = ("BUILD", "FIX FIRST", "KILL")
REQUIRED_FIELDS = ("id", "slug", "idea", "date", "verdict", "biggest_risk", "open_questions")
SEAT_HEADINGS = ("## Believer", "## Skeptic", "## Investor", "## Judge")
VERDICT_LINE_RE = re.compile(r"^\*\*VERDICT:\*\*[ \t]*(?P<verdict>[^\r\n]*)$", re.MULTILINE)
BIGGEST_RISK_LINE_RE = re.compile(r"^\*\*Biggest risk:\*\*[ \t]*(?P<risk>[^\r\n]*)$", re.MULTILINE)
TEST_LINE_RE = re.compile(r"^\*\*10-minute test:\*\*[ \t]*(?P<test>[^\r\n]*)$", re.MULTILINE)
FLIP_LINE_RE = re.compile(r"^\*\*Flips to BUILD if:\*\*", re.MULTILINE)
# The bullet list runs to the first line that is neither blank nor a bullet, so it must be
# the last thing in the file (the template puts it last on purpose).
OPEN_QUESTIONS_RE = re.compile(
    r"^\*\*Open questions carried forward:\*\*[ \t]*\r?\n(?P<body>(?:[ \t]*(?:-.*)?\r?\n)*)",
    re.MULTILINE,
)


class RoastLogError(Exception):
    """A ruling on disk is malformed."""


@dataclass(frozen=True)
class Ruling:
    """One parsed, validated ruling file."""

    id: str
    slug: str
    idea: str
    date: str
    verdict: str
    biggest_risk: str
    open_questions: int
    path: Path

    @property
    def filename(self) -> str:
        return self.path.name

    @property
    def link(self) -> str:
        return f"[{self.filename}]({self.filename})"

    def index_row(self) -> list[str]:
        return [
            self.id,
            self.idea,
            self.date,
            self.verdict,
            self.biggest_risk,
            str(self.open_questions),
            self.link,
        ]


def parse_frontmatter(text: str, path: Path) -> dict[str, str]:
    """Return the flat ``key: value`` frontmatter block of a ruling file."""
    match = FRONTMATTER_RE.match(text)
    if match is None:
        raise RoastLogError(f"{path}: missing a YAML frontmatter block delimited by '---'")

    fields: dict[str, str] = {}
    for lineno, raw in enumerate(match.group("body").splitlines(), start=2):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            raise RoastLogError(
                f"{path}:{lineno}: expected 'key: value', got {raw!r} "
                "(frontmatter values must stay on one line)"
            )
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if not key:
            raise RoastLogError(f"{path}:{lineno}: empty frontmatter key")
        if key in fields:
            raise RoastLogError(f"{path}:{lineno}: duplicate frontmatter key {key!r}")
        fields[key] = value
    return fields


def _single_line(value: str, field: str, path: Path) -> str:
    if "|" in value:
        raise RoastLogError(
            f"{path}: frontmatter field {field!r} contains a '|', which breaks the index table"
        )
    return value


def validate_ruling_body(text: str, path: Path, verdict: str) -> int:
    """Validate the human-readable half of a ruling; return its open-question count."""
    positions = []
    for heading in SEAT_HEADINGS:
        index = text.find(f"\n{heading}")
        if index == -1:
            raise RoastLogError(f"{path}: missing required section heading {heading!r}")
        positions.append(index)
    if positions != sorted(positions):
        found = ", ".join(SEAT_HEADINGS)
        raise RoastLogError(f"{path}: seat headings are out of order; expected {found} in that order")

    verdict_line = VERDICT_LINE_RE.search(text)
    if verdict_line is None:
        raise RoastLogError(f"{path}: the Judge section must state '**VERDICT:** <verdict>'")
    stated = verdict_line.group("verdict").strip().strip("`").strip()
    if stated.upper() != verdict.upper():
        raise RoastLogError(
            f"{path}: the Judge section says VERDICT {stated!r} but frontmatter says {verdict!r}"
        )

    if not BIGGEST_RISK_LINE_RE.search(text):
        raise RoastLogError(f"{path}: the Judge section must state '**Biggest risk:** ...'")
    if not TEST_LINE_RE.search(text):
        raise RoastLogError(f"{path}: the Judge section must state '**10-minute test:** ...'")
    if verdict.upper() == "FIX FIRST" and not FLIP_LINE_RE.search(text):
        raise RoastLogError(
            f"{path}: a FIX FIRST ruling must state '**Flips to BUILD if:** ...'"
        )

    questions = OPEN_QUESTIONS_RE.search(text)
    if questions is None:
        raise RoastLogError(
            f"{path}: the Judge section must end with an '**Open questions carried forward:**' list"
        )
    return sum(1 for line in questions.group("body").splitlines() if line.strip().startswith("-"))


def load_ruling(path: Path) -> Ruling:
    """Parse and validate one ruling file."""
    text = path.read_text(encoding="utf-8")

    name_match = RULING_FILENAME_RE.match(path.name)
    if name_match is None:
        raise RoastLogError(
            f"{path}: ruling filenames must look like '001-some-idea.md' "
            "(three digits, hyphen, kebab-case slug)"
        )

    fields = parse_frontmatter(text, path)
    for field in REQUIRED_FIELDS:
        if not fields.get(field):
            raise RoastLogError(f"{path}: frontmatter is missing a non-empty {field!r} field")

    if fields["id"] != name_match.group("id"):
        raise RoastLogError(
            f"{path}: frontmatter id {fields['id']!r} does not match the filename prefix "
            f"{name_match.group('id')!r}"
        )
    if fields["slug"] != name_match.group("slug"):
        raise RoastLogError(
            f"{path}: frontmatter slug {fields['slug']!r} does not match the filename slug "
            f"{name_match.group('slug')!r}"
        )
    if not SLUG_RE.match(fields["slug"]):
        raise RoastLogError(f"{path}: slug {fields['slug']!r} must be kebab-case")
    if not DATE_RE.match(fields["date"]):
        raise RoastLogError(f"{path}: date {fields['date']!r} must be YYYY-MM-DD")

    verdict = fields["verdict"].upper()
    if verdict not in VERDICTS:
        raise RoastLogError(
            f"{path}: verdict {fields['verdict']!r} is not one of {', '.join(VERDICTS)}"
        )

    idea = _single_line(fields["idea"], "idea", path)
    biggest_risk = _single_line(fields["biggest_risk"], "biggest_risk", path)

    try:
        open_questions = int(fields["open_questions"])
    except ValueError as exc:
        raise RoastLogError(
            f"{path}: open_questions {fields['open_questions']!r} must be an integer"
        ) from exc
    if open_questions < 0:
        raise RoastLogError(f"{path}: open_questions must not be negative")

    body_count = validate_ruling_body(text, path, verdict)
    if body_count != open_questions:
        raise RoastLogError(
            f"{path}: frontmatter says open_questions: {open_questions} but the Judge section "
            f"lists {body_count} bullet(s)"
        )

    return Ruling(
        id=fields["id"],
        slug=fields["slug"],
        idea=idea,
        date=fields["date"],
        verdict=verdict,
        biggest_risk=biggest_risk,
        open_questions=open_questions,
        path=path,
    )


def discover_rulings(roasts_dir: Path) -> list[Ruling]:
    """Load every ruling in ``roasts_dir``, sorted by id, rejecting duplicate ids."""
    rulings: list[Ruling] = []
    for path in sorted(roasts_dir.glob("*.md")):
        if not RULING_FILENAME_RE.match(path.name):
            continue  # README.md, TEMPLATE.md, INDEX.md, _inbox.md are not rulings
        rulings.append(load_ruling(path))

    rulings.sort(key=lambda ruling: ruling.id)
    seen: dict[str, Path] = {}
    for ruling in rulings:
        if ruling.id in seen:
            raise RoastLogError(
                f"{ruling.path}: id {ruling.id!r} is already used by {seen[ruling.id]}"
            )
        seen[ruling.id] = ruling.path
    return rulings


def _cells(line: str) -> list[str]:
    stripped = line.strip()
    if stripped.startswith("|"):
        stripped = stripped[1:]
    if stripped.endswith("|"):
        stripped = stripped[:-1]
    return [" ".join(cell.split()) for cell in stripped.split("|")]


def _is_separator(cells: list[str]) -> bool:
    return bool(cells) and all(re.fullmatch(r":?-{2,}:?", cell) for cell in cells)


def _is_header(cells: list[str]) -> bool:
    return [cell.lower() for cell in cells] == [column.lower() for column in INDEX_HEADER]


def render_table(rulings: list[Ruling]) -> str:
    """Render the markdown table for the given rulings."""
    lines = [
        "| " + " | ".join(INDEX_HEADER) + " |",
        "| " + " | ".join(":---" for _ in INDEX_HEADER) + " |",
    ]
    lines.extend("| " + " | ".join(ruling.index_row()) + " |" for ruling in rulings)
    return "\n".join(lines)


def actual_rows(index_text: str, path: Path) -> list[list[str]]:
    """Return the data rows currently written between the index markers."""
    start = index_text.find(INDEX_BEGIN)
    end = index_text.find(INDEX_END)
    if start == -1 or end == -1 or end < start:
        raise RoastLogError(
            f"{path}: missing the '{INDEX_BEGIN}' / '{INDEX_END}' markers that bracket the table"
        )

    rows: list[list[str]] = []
    for line in index_text[start + len(INDEX_BEGIN) : end].splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = _cells(line)
        if _is_header(cells) or _is_separator(cells):
            continue
        rows.append(cells)
    return rows


def check_index(rulings: list[Ruling], index_text: str, index_path: Path) -> list[str]:
    """Return a list of human-readable drift problems (empty means in sync)."""
    expected = [ruling.index_row() for ruling in rulings]
    actual = actual_rows(index_text, index_path)

    if len(actual) != len(expected):
        return [
            f"{index_path}: has {len(actual)} row(s) but there are {len(expected)} ruling file(s); "
            "run 'python scripts/roast_index.py' to regenerate the table"
        ]

    problems: list[str] = []
    for expected_row, actual_row in zip(expected, actual):
        if expected_row == actual_row:
            continue
        for column, expected_cell, actual_cell in zip(INDEX_HEADER, expected_row, actual_row):
            if expected_cell != actual_cell:
                problems.append(
                    f"{index_path}: row {expected_row[0]} column {column!r} says {actual_cell!r} "
                    f"but the ruling says {expected_cell!r}"
                )
    return problems


def render_index(existing: str | None, rulings: list[Ruling]) -> str:
    """Return INDEX.md content with its generated table replaced."""
    table = render_table(rulings)
    region = f"{INDEX_BEGIN}\n\n{table}\n\n{INDEX_END}"

    if existing:
        start = existing.find(INDEX_BEGIN)
        end = existing.find(INDEX_END)
        if start != -1 and end != -1 and end > start:
            return existing[:start] + region + existing[end + len(INDEX_END) :]

    return f"{INDEX_PREAMBLE}{region}\n"


def find_problems(roasts_dir: Path) -> list[str]:
    """Validate every ruling and its index; return an empty list when all is well."""
    index_path = roasts_dir / "INDEX.md"
    rulings = discover_rulings(roasts_dir)

    if not index_path.exists():
        return [
            f"{index_path}: does not exist; run 'python scripts/roast_index.py' to generate it"
        ]
    return check_index(rulings, index_path.read_text(encoding="utf-8"), index_path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify INDEX.md matches the rulings instead of rewriting it",
    )
    parser.add_argument(
        "--roasts-dir",
        type=Path,
        default=REPO_ROOT / "roasts",
        help="directory holding the rulings (default: <repo>/roasts)",
    )
    args = parser.parse_args(argv)
    roasts_dir: Path = args.roasts_dir
    index_path = roasts_dir / "INDEX.md"

    try:
        rulings = discover_rulings(roasts_dir)
    except RoastLogError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.check:
        try:
            problems = find_problems(roasts_dir)
        except RoastLogError as error:
            print(f"error: {error}", file=sys.stderr)
            return 2
        if problems:
            for problem in problems:
                print(f"error: {problem}", file=sys.stderr)
            return 1
        print(f"ok: {len(rulings)} ruling(s) and INDEX.md agree")
        return 0

    existing = index_path.read_text(encoding="utf-8") if index_path.exists() else None
    index_path.write_text(render_index(existing, rulings), encoding="utf-8")
    print(f"wrote {index_path} with {len(rulings)} ruling(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
